### PR TITLE
Fixed articles creation and moved to the backend section

### PR DESCRIPTION
**Pull request by luffygujjar**
Updates:  @mua22 

1: Fixed article creation.
2: A separate namespace for backend views (using admin lte)
3: Only admin can create articles.
4: Small fixes.

### CODE REVIEW

**Comment by mua22** [comment]
Luffy Gujjar: Whos this

**Comment by luffygujjar** [comment]
Your web development course student. FA12-130, section B.

**Comment by mua22** [comment]
Add me to your facebook and join my class group

**Comment by mua22** [comment]
Sher Afghan ? 
Check latest commit. I have added a new command . Give it a go and see if you find anything missing. 
It automatically detects the column names and make a view for boilerplating

**Pull request merged**
